on: [push]

name: AzureARMDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Create Bicep Parameters File
      run: |
        cat > ./main.parameters.json <<EOL
        {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
            "adminPassword": {
              "value": "${{ secrets.ADMIN_PASSWORD }}"
            },
            "sqlAdminPassword": {
              "value": "${{ secrets.SQL_PASS }}"
            }
          }
        }
        EOL

    - name: Deploy Bicep File
      uses: azure/arm-deploy@v2 # Make sure this is v2
      with:
        resourceGroupName: 3tierwebapp
        template: ./main.bicep
        parameters: ./main.parameters.json
          
